version: '3.7'

services:
  postgesql:
    image: 'postgres:14.1-alpine'
    container_name: postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=power-sso
    volumes:
      - postgres_data:/data/postgres
    networks:
      - powersso
    
  mailcatcher:
    container_name: mailcatcher
    image: sj26/mailcatcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025
      - 1080:1080

networks:
  powersso:
    driver: bridge

volumes:
  postgres_data:
