version: '3.7'

services:
  postgesql:
    image: 'postgres:14.1-alpine'
    container_name: postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=power-sso
    volumes:
      - postgres_data:/data/postgres
    networks:
      - powersso
    
  mailcatcher:
    container_name: mailcatcher
    image: sj26/mailcatcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025
      - 1080:1080

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5555:5555"
    depends_on:
      - postgesql
    restart: always
    environment:
      - CONFIG_POWER_SSO=/etc/powersso/app.json
      - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn
    volumes:
      - /etc/powersso:/etc/powersso
      - logs:/var/log/powersso
      - ${CONFIG_POWER_SSO:-/etc/powersso/app.json}:/etc/powersso/app.json
    networks:
      - powersso

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./ui/build:/app/frontend/build
    networks:
      - powersso

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost/api/v1/
    env_file:
      - ./ui/.env 
    networks:
      - powersso

networks:
  powersso:
    driver: bridge

volumes:
  postgres_data:
  logs:
