meta:
  ProjectName: "PowerSSO"
  ProjectURL: "http://localhost:3000"

server:
  Version: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: testing
  JwtSecretKey: power-sso-secret
  CookieName: jwt-power-sso
  SSL: false
  CtxDefaultTimeout: 12
  ReadTimeout: 5
  WriteTimeout: 5
  CSRF: true
  Debug: false
  AccessLogDirectory: /var/log/power-sso/access.log
  ErrorLogDirectory: /var/log/power-sso/error.log
  PermissionBase: github.com/isaqueveras/power-sso

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: power-sso
  Sslmode: false
  Driver: pgx
  MaxOpenConns: 60
  MaxIdleConns: 30
  ConnMaxLifetime: 120
  ConnMaxIdleTime: 20
  Timeout: 2

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

mailer:
  Host: localhost
  Port: 1025
  Email: contact@powersso.io
  Password: password
  TLS: false

UserAuthToken:
  SecretKey: kjnfdjksdbfsdhfbdskjfnamkndkn 
  Duration: 2592000