server:
  Version: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: power-sso-secret
  CookieName: jwt-power-sso
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: power_sso
  Sslmode: false
  Driver: pgx