server:
  Version: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: development
  JwtSecretKey: power-sso-secret
  CookieName: jwt-power-sso
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  AccessLogDirectory: /var/log/power-sso/access.log
  ErrorLogDirectory: /var/log/power-sso/error.log
  PermissionBase: github.com/isaqueveras/power-sso

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: power_sso
  Sslmode: false
  Driver: pgx

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info